Prevent symfony/event-dispatcher great than 4.2 from being installed
This is in order to prevent the following notice from being thrown:

NoticedError: Calling the
"Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()"
method with the event name as the first argument is deprecated since
Symfony 4.3, pass it as the second argument and provide the event object
as the first argument instead.